
module test:
    snakefile:
        "https://raw.githubusercontent.com/ismk/ismk/v6.3.0/tests/test_report/Snakefile"
    config:
        config
    replace_prefix: 
        {"results/": "results/testmodule/"}


use rule * from test
