shell.executable("bash")

import pandas as pd
from ismk.utils import validate


validate(config, "config.schema.yaml")


rule a:
    output:
        "test.{sample}.txt",
    shell:
        "touch {output}"
